name: Deploy Cat Website

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Download repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t catwebsite .

      - name: Run container
        run: docker run -d -p 80:80 catwebsite