name: Build and Run Cat Website Locally

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t imagecatwebsite:latest .

      - name: Run container
        run: docker run -d -p 8080:80 imagecatwebsite:latest

      - name: Show running containers
        run: docker ps